version: "3.7"

services:
  <$DOCKER_NAME>:
    build:
      context: .
      dockerfile: Dockerfile
      args:
              BUILD_NUMBER: ${BUILD_NUMBER}
    volumes:
      - ./code_python:/home/code_python
      - ./app:/home/app
    user: root
    restart: "no"
